targets:
  compile:
    cmd: make
    sh: true
  clean:
    cmd: make
    args:
      - clean
    sh: true
  rebuild-cache:
    cmd: make
    args:
      - rebuild_cache
    sh: true
  compile-and-flash:
    cmd: make && arm-none-eabi-objcopy -O ihex blinky blinky.hex && st-flash --format ihex write blinky.hex
    sh: true
